package nvueschema

import (
	"fmt"
	"io"
	"strings"
)

// WriteProtobuf outputs the config schema as a .proto file.
// If validate is true, buf protovalidate constraints are included.
func WriteProtobuf(w io.Writer, schema *Config, info map[string]any, validate bool) error {
	g := &protoGen{
		w:        w,
		messages: make(map[string]bool),
		validate: validate,
	}

	fmt.Fprintln(w, `// Code generated by cumulus-schema. DO NOT EDIT.`)
	if v, ok := info["version"].(string); ok {
		fmt.Fprintf(w, "// Generated from NVUE OpenAPI spec version %s\n", v)
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, `syntax = "proto3";`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package nvue.v1;`)
	fmt.Fprintln(w)
	if validate {
		fmt.Fprintln(w, `import "buf/validate/validate.proto";`)
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, `option go_package = "nvue/v1;nvuev1";`)
	fmt.Fprintln(w)

	g.emitMessage("NvueConfig", schema, 0)

	return nil
}

type protoGen struct {
	w        io.Writer
	messages map[string]bool
	validate bool
}

func (g *protoGen) emitMessage(name string, s *Config, depth int) {
	if g.messages[name] {
		return
	}
	g.messages[name] = true

	merged := FlattenComposite(s)
	indent := strings.Repeat("  ", depth)
	props := sortedProperties(merged)

	// Emit nested messages for child structs first.
	var nested []struct {
		msgName string
		schema  *Config
	}
	for _, p := range props {
		childName := toPascal(p.name)
		if isScalarUnion(p.schema) {
			continue
		}
		flat := FlattenComposite(p.schema)
		if hasProps(flat) {
			nested = append(nested, struct {
				msgName string
				schema  *Config
			}{childName, p.schema})
		}
		if flat.AdditionalProperties != nil {
			apFlat := FlattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				nested = append(nested, struct {
					msgName string
					schema  *Config
				}{childName + "Entry", flat.AdditionalProperties})
			}
		}
	}

	// Emit the message.
	if merged.Description != "" {
		for line := range strings.SplitSeq(strings.TrimRight(merged.Description, "\n"), "\n") {
			fmt.Fprintf(g.w, "%s// %s\n", indent, line)
		}
	}
	ref := sourceRefFor(s)
	if ref != "" {
		fmt.Fprintf(g.w, "%s// Path: %s\n", indent, ref)
	}
	fmt.Fprintf(g.w, "%smessage %s {\n", indent, name)

	// Emit nested messages inside this message.
	for _, n := range nested {
		g.emitMessage(n.msgName, n.schema, depth+1)
	}

	// Emit fields.
	fieldNum := 1
	for i, p := range props {
		flat := FlattenComposite(p.schema)
		protoType := g.protoType(p.name, p.schema)
		fieldName := protoFieldName(p.name)

		constraint := ""
		if g.validate {
			constraint = g.protoConstraint(p.schema)
		}

		if i > 0 {
			fmt.Fprintln(g.w)
		}
		if flat.Description != "" {
			for line := range strings.SplitSeq(strings.TrimRight(flat.Description, "\n"), "\n") {
				fmt.Fprintf(g.w, "%s  // %s\n", indent, line)
			}
		}

		switch {
		case protoType.repeated:
			fmt.Fprintf(g.w, "%s  repeated %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		case protoType.isMap:
			fmt.Fprintf(g.w, "%s  map<string, %s> %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		case protoType.optional:
			fmt.Fprintf(g.w, "%s  optional %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		default:
			fmt.Fprintf(g.w, "%s  %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		}
		fieldNum++
	}

	fmt.Fprintf(g.w, "%s}\n\n", indent)
}

type protoTypeInfo struct {
	typeName string
	optional bool
	repeated bool
	isMap    bool
}

func (g *protoGen) protoType(contextName string, s *Config) protoTypeInfo {
	if s == nil {
		return protoTypeInfo{typeName: "string", optional: true}
	}

	if isScalarUnion(s) {
		// Proto doesn't have unions for scalars; use string as the most permissive.
		return protoTypeInfo{typeName: "string", optional: true}
	}

	flat := FlattenComposite(s)

	if len(flat.Enum) > 0 {
		return protoTypeInfo{typeName: "string", optional: true}
	}

	// Check format.
	if ft := formatToProtoType(flat.Format); ft != "" {
		return protoTypeInfo{typeName: ft, optional: true}
	}

	switch flat.Type {
	case "string":
		return protoTypeInfo{typeName: "string", optional: true}
	case "integer":
		return protoTypeInfo{typeName: "int64", optional: true}
	case "number":
		return protoTypeInfo{typeName: "double", optional: true}
	case "boolean":
		return protoTypeInfo{typeName: "bool", optional: true}
	case "array":
		inner := g.protoType(contextName+"Item", flat.Items)
		return protoTypeInfo{typeName: inner.typeName, repeated: true}
	case "object":
		if hasProps(flat) {
			return protoTypeInfo{typeName: toPascal(contextName), optional: true}
		}
		if flat.AdditionalProperties != nil {
			apFlat := FlattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				return protoTypeInfo{typeName: toPascal(contextName) + "Entry", isMap: true}
			}
			inner := g.protoType(contextName+"Entry", flat.AdditionalProperties)
			return protoTypeInfo{typeName: inner.typeName, isMap: true}
		}
		return protoTypeInfo{typeName: "string", isMap: true}
	}

	if hasProps(flat) {
		return protoTypeInfo{typeName: toPascal(contextName), optional: true}
	}
	if flat.AdditionalProperties != nil {
		apFlat := FlattenComposite(flat.AdditionalProperties)
		if hasProps(apFlat) {
			return protoTypeInfo{typeName: toPascal(contextName) + "Entry", isMap: true}
		}
		inner := g.protoType(contextName+"Entry", flat.AdditionalProperties)
		return protoTypeInfo{typeName: inner.typeName, isMap: true}
	}

	return protoTypeInfo{typeName: "string", optional: true}
}

func (g *protoGen) protoConstraint(s *Config) string {
	if !g.validate {
		return ""
	}

	flat := FlattenComposite(s)

	var parts []string

	// String constraints.
	if flat.Type == "string" || flat.Format != "" {
		if flat.Pattern != "" {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.pattern = %q", flat.Pattern))
		}
		if flat.MinLength != nil && *flat.MinLength > 0 {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.min_len = %d", *flat.MinLength))
		}
		if flat.MaxLength != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.max_len = %d", *flat.MaxLength))
		}
		// Format-based pattern.
		if pat := formatToProtoPattern(flat.Format); pat != "" && flat.Pattern == "" {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.pattern = %q", pat))
		}
		// Built-in validators.
		k := formatKeyFor(flat.Format)
		switch k {
		case fmtIPv4Addr:
			parts = append(parts, "(buf.validate.field).string.ipv4 = true")
		case fmtIPv6Addr:
			parts = append(parts, "(buf.validate.field).string.ipv6 = true")
		case fmtHostname:
			parts = append(parts, "(buf.validate.field).string.hostname = true")
		}
	}

	// Integer constraints.
	if flat.Type == "integer" {
		if flat.Minimum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).int64.gte = %d", int64(*flat.Minimum)))
		}
		if flat.Maximum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).int64.lte = %d", int64(*flat.Maximum)))
		}
	}

	// Number constraints.
	if flat.Type == "number" {
		if flat.Minimum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).double.gte = %s", fmtNum(*flat.Minimum)))
		}
		if flat.Maximum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).double.lte = %s", fmtNum(*flat.Maximum)))
		}
	}

	if len(parts) == 0 {
		return ""
	}
	return " [" + strings.Join(parts, ", ") + "]"
}

// formatToProtoType maps format strings to proto scalar types via the registry.
func formatToProtoType(format string) string {
	k := formatKeyFor(format)
	if k == 0 {
		return ""
	}
	if t, ok := protoFormatTypes[k]; ok {
		return t
	}
	return ""
}

var protoFormatTypes = map[formatKey]string{
	fmtInteger:    "int64",
	fmtSequenceID: "int64",
	fmtFloat:      "double",
}

// formatToProtoPattern returns the validation pattern for a format via the registry.
func formatToProtoPattern(format string) string {
	k := formatKeyFor(format)
	if k == 0 {
		return ""
	}
	td := typedefFor(k)
	if td == nil || td.pattern == "" {
		return ""
	}
	return td.pattern
}

func protoFieldName(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	// Proto field names must start with a letter.
	if len(s) > 0 && s[0] >= '0' && s[0] <= '9' {
		s = "x_" + s
	}
	return s
}
