package nvueschema

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strings"
	"unicode"
)

const goLineWidth = 88

// WriteGoStructs outputs the config schema as Go struct definitions with json tags.
func WriteGoStructs(w io.Writer, schema *Config, info map[string]any) error {
	var buf bytes.Buffer
	g := &goGen{
		w:      &buf,
		models: make(map[string]bool),
	}

	fmt.Fprintln(&buf, "// Code generated by cumulus-schema. DO NOT EDIT.")
	if v, ok := info["version"].(string); ok {
		fmt.Fprintf(&buf, "// Generated from NVUE OpenAPI spec version %s\n", v)
	}
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package nvue")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "import (")
	fmt.Fprintln(&buf, "\t\"net/netip\"")
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)

	// Emit type aliases for validated string types.
	fmt.Fprintln(&buf, "// Validated string types for network configuration values.")
	fmt.Fprintln(&buf, "// Use the Validate() methods or a JSON Schema validator to enforce patterns.")
	for _, td := range goTypedefs {
		fmt.Fprintf(&buf, "type %s = string\n", td.name)
	}
	fmt.Fprintln(&buf)

	g.emitStruct("NvueConfig", schema)

	// Run go fmt on the output.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write the raw output so the user can debug.
		_, writeErr := w.Write(buf.Bytes())
		if writeErr != nil {
			return writeErr
		}
		return fmt.Errorf("go format: %w", err)
	}
	_, err = w.Write(formatted)
	return err
}

var goTypedefs = []struct {
	name    string
	pattern string
}{
	{"MacAddress", `^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`},
	{"InterfaceName", `^(swp|eth|bond|br|lo|vlan|peerlink|erspan|mgmt)[a-zA-Z0-9_./-]*$`},
	{"VrfName", `^[a-zA-Z][a-zA-Z0-9_-]{0,14}$`},
	{"VlanRange", `^[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*$`},
	{"PortRange", `^[0-9]+(-[0-9]+)?$`},
	{"RouteDistinguisher", `^(\d+\.\d+\.\d+\.\d+:\d+|\d+:\d+)$`},
	{"RouteTarget", `^(\d+\.\d+\.\d+\.\d+:\d+|\d+:\d+)$`},
	{"ExtCommunity", `^(rt|soo|bandwidth)\s+\S+$`},
	{"BgpCommunity", `^(\d+:\d+|no-export|no-advertise|local-AS|no-peer|blackhole|graceful-shutdown|accept-own|internet)$`},
	{"EvpnRoute", `^(macip|imet|prefix)$`},
	{"BgpRegex", ``},
	{"AsnRange", `^(\d+|\d+-\d+)(,(\d+|\d+-\d+))*$`},
	{"EsIdentifier", `^([0-9A-Fa-f]{2}:){9}[0-9A-Fa-f]{2}$`},
	{"SegmentIdentifier", `^\d+$`},
	{"Hostname", `^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$`},
	{"UserName", `^[a-z_][a-z0-9_-]*[$]?$`},
	{"SnmpOid", `^\.?(\d+\.)*\d+$`},
}

type goGen struct {
	w      io.Writer
	models map[string]bool
}

func (g *goGen) emitStruct(name string, s *Config) {
	if g.models[name] {
		return
	}
	g.models[name] = true

	merged := FlattenComposite(s)

	type propEntry struct {
		name   string
		schema *Config
	}
	var props []propEntry
	if merged.Properties != nil {
		for k, v := range merged.Properties {
			props = append(props, propEntry{k, v})
		}
		sort.Slice(props, func(i, j int) bool { return props[i].name < props[j].name })
	}

	// Emit child structs first (depth-first).
	for _, p := range props {
		childName := name + goPublic(p.name)
		if isScalarUnion(p.schema) {
			continue
		}
		flat := FlattenComposite(p.schema)
		if hasProps(flat) {
			g.emitStruct(childName, p.schema)
		}
		if flat.AdditionalProperties != nil {
			apFlat := FlattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				g.emitStruct(childName+"Entry", flat.AdditionalProperties)
			}
		}
	}

	// Emit this struct.
	if merged.Description != "" {
		writeWrappedComment(g.w, merged.Description, "// ", goLineWidth)
	}
	ref := sourceRefFor(s)
	if ref != "" {
		fmt.Fprintf(g.w, "// Path: %s\n", ref)
	}
	fmt.Fprintf(g.w, "type %s struct {\n", name)

	for i, p := range props {
		goType := g.goType(name+goPublic(p.name), p.schema)
		fieldName := goPublic(p.name)
		jsonTag := p.name

		flat := FlattenComposite(p.schema)

		if i > 0 {
			fmt.Fprintln(g.w)
		}
		if flat.Description != "" {
			writeWrappedComment(g.w, flat.Description, "\t// ", goLineWidth)
		}
		fmt.Fprintf(g.w, "\t%s %s `json:\"%s,omitempty\" yaml:\"%s,omitempty\"`\n", fieldName, goType, jsonTag, jsonTag)
	}

	fmt.Fprintln(g.w, "}")
	fmt.Fprintln(g.w)
}

func (g *goGen) goType(contextName string, s *Config) string {
	if s == nil {
		return "any"
	}

	if isScalarUnion(s) {
		return "any" // Go doesn't have union types; any is the honest answer
	}

	flat := FlattenComposite(s)

	if len(flat.Enum) > 0 {
		return "string"
	}

	// Check format first.
	if ft := formatToGoType(flat.Format); ft != "" {
		return "*" + ft
	}

	switch flat.Type {
	case "string":
		return "*string"
	case "integer":
		return "*int64"
	case "number":
		return "*float64"
	case "boolean":
		return "*bool"
	case "array":
		inner := g.goType(contextName+"Item", flat.Items)
		// Strip pointer from inner type for slices.
		inner = strings.TrimPrefix(inner, "*")
		return "[]" + inner
	case "object":
		if hasProps(flat) {
			return "*" + contextName
		}
		if flat.AdditionalProperties != nil {
			apFlat := FlattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				return "map[string]*" + contextName + "Entry"
			}
			valType := g.goType(contextName+"Entry", flat.AdditionalProperties)
			valType = strings.TrimPrefix(valType, "*")
			return "map[string]" + valType
		}
		return "map[string]any"
	}

	if hasProps(flat) {
		return "*" + contextName
	}
	if flat.AdditionalProperties != nil {
		apFlat := FlattenComposite(flat.AdditionalProperties)
		if hasProps(apFlat) {
			return "map[string]*" + contextName + "Entry"
		}
		valType := g.goType(contextName+"Entry", flat.AdditionalProperties)
		valType = strings.TrimPrefix(valType, "*")
		return "map[string]" + valType
	}

	return "any"
}

func formatToGoType(format string) string {
	switch format {
	case "ipv4", "ipv4-unicast", "ipv4-multicast", "ipv4-netmask":
		return "netip.Addr"
	case "ipv6", "ipv6-netmask":
		return "netip.Addr"
	case "dns-server-ip-address":
		return "netip.Addr"
	case "ipv4-prefix", "ipv4-sub-prefix", "ipv4-multicast-prefix",
		"aggregate-ipv4-prefix":
		return "netip.Prefix"
	case "ipv6-prefix", "ipv6-sub-prefix", "aggregate-ipv6-prefix":
		return "netip.Prefix"
	case "mac":
		return "MacAddress"
	case "interface-name", "swp-name", "bond-swp-name", "transceiver-name",
		"bridge-name":
		return "InterfaceName"
	case "vrf-name":
		return "VrfName"
	case "vlan-range":
		return "VlanRange"
	case "ip-port-range":
		return "PortRange"
	case "route-distinguisher":
		return "RouteDistinguisher"
	case "route-target", "route-target-any":
		return "RouteTarget"
	case "ext-community":
		return "ExtCommunity"
	case "community", "well-known-community", "large-community":
		return "BgpCommunity"
	case "evpn-route":
		return "EvpnRoute"
	case "bgp-regex":
		return "BgpRegex"
	case "asn-range":
		return "AsnRange"
	case "es-identifier":
		return "EsIdentifier"
	case "segment-identifier":
		return "SegmentIdentifier"
	case "idn-hostname", "domain-name":
		return "Hostname"
	case "user-name":
		return "UserName"
	case "snmp-branch", "oid":
		return "SnmpOid"
	case "secret-string", "key-string":
		return "string"
	case "integer", "integer-id", "sequence-id":
		return "int64"
	case "float", "number":
		return "float64"
	default:
		return ""
	}
}

// goPublic converts a kebab-case or snake_case name to a Go public identifier.
func goPublic(s string) string {
	parts := strings.FieldsFunc(s, func(c rune) bool {
		return c == '-' || c == '_' || c == '.'
	})
	for i, p := range parts {
		if len(p) == 0 {
			continue
		}
		// Handle well-known acronyms.
		upper := strings.ToUpper(p)
		if goAcronyms[upper] {
			parts[i] = upper
		} else {
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			parts[i] = string(runes)
		}
	}
	name := strings.Join(parts, "")
	// Prefix with X if it starts with a digit.
	if len(name) > 0 && name[0] >= '0' && name[0] <= '9' {
		name = "X" + name
	}
	return name
}

// goAcronyms is the set of well-known acronyms for Go identifier generation.
var goAcronyms = map[string]bool{
	"ID": true, "IP": true, "TCP": true, "UDP": true, "HTTP": true,
	"HTTPS": true, "URL": true, "API": true, "DNS": true, "MAC": true,
	"VLAN": true, "VRF": true, "BGP": true, "OSPF": true, "EVPN": true,
	"ACL": true, "MTU": true, "TTL": true, "QOS": true, "PTP": true,
	"SNMP": true, "SSH": true, "NTP": true, "DHCP": true, "IGMP": true,
	"MLAG": true, "NVE": true, "VNI": true, "STP": true, "LLDP": true,
}

// writeWrappedComment writes text as comment lines, wrapping at maxWidth.
func writeWrappedComment(w io.Writer, text string, prefix string, maxWidth int) {
	text = strings.TrimRight(text, "\n")
	contentWidth := max(maxWidth-len(prefix), 20)

	for paragraph := range strings.SplitSeq(text, "\n") {
		paragraph = strings.TrimSpace(paragraph)
		if paragraph == "" {
			fmt.Fprintf(w, "%s\n", strings.TrimRight(prefix, " "))
			continue
		}

		words := strings.Fields(paragraph)
		line := ""
		for _, word := range words {
			switch {
			case line == "":
				line = word
			case len(line)+1+len(word) <= contentWidth:
				line += " " + word
			default:
				fmt.Fprintf(w, "%s%s\n", prefix, line)
				line = word
			}
		}
		if line != "" {
			fmt.Fprintf(w, "%s%s\n", prefix, line)
		}
	}
}
