package main

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// WriteProtobuf outputs the config schema as a .proto file.
// If validate is true, buf protovalidate constraints are included.
func WriteProtobuf(w io.Writer, schema *Schema, info map[string]any, validate bool) error {
	g := &protoGen{
		w:        w,
		messages: make(map[string]bool),
		validate: validate,
	}

	fmt.Fprintln(w, `// Code generated by cumulus-schema. DO NOT EDIT.`)
	if v, ok := info["version"].(string); ok {
		fmt.Fprintf(w, "// Generated from NVUE OpenAPI spec version %s\n", v)
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, `syntax = "proto3";`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package nvue.v1;`)
	fmt.Fprintln(w)
	if validate {
		fmt.Fprintln(w, `import "buf/validate/validate.proto";`)
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, `option go_package = "nvue/v1;nvuev1";`)
	fmt.Fprintln(w)

	g.emitMessage("NvueConfig", schema, 0)

	return nil
}

type protoGen struct {
	w        io.Writer
	messages map[string]bool
	validate bool
	fieldNum int
}

func (g *protoGen) emitMessage(name string, s *Schema, depth int) {
	if g.messages[name] {
		return
	}
	g.messages[name] = true

	merged := flattenComposite(s)
	indent := strings.Repeat("  ", depth)

	type propEntry struct {
		name   string
		schema *Schema
	}
	var props []propEntry
	if merged.Properties != nil {
		for k, v := range merged.Properties {
			props = append(props, propEntry{k, v})
		}
		sort.Slice(props, func(i, j int) bool { return props[i].name < props[j].name })
	}

	// Emit nested messages for child structs first.
	var nested []struct {
		msgName string
		schema  *Schema
	}
	for _, p := range props {
		childName := protoMessageName(p.name)
		if isScalarUnion(p.schema) {
			continue
		}
		flat := flattenComposite(p.schema)
		if hasProps(flat) {
			nested = append(nested, struct {
				msgName string
				schema  *Schema
			}{childName, p.schema})
		}
		if flat.AdditionalProperties != nil {
			apFlat := flattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				nested = append(nested, struct {
					msgName string
					schema  *Schema
				}{childName + "Entry", flat.AdditionalProperties})
			}
		}
	}

	// Emit the message.
	if merged.Description != "" {
		for _, line := range strings.Split(strings.TrimRight(merged.Description, "\n"), "\n") {
			fmt.Fprintf(g.w, "%s// %s\n", indent, line)
		}
	}
	ref := sourceRefFor(s)
	if ref != "" {
		fmt.Fprintf(g.w, "%s// Path: %s\n", indent, ref)
	}
	fmt.Fprintf(g.w, "%smessage %s {\n", indent, name)

	// Emit nested messages inside this message.
	for _, n := range nested {
		g.emitMessage(n.msgName, n.schema, depth+1)
	}

	// Emit fields.
	fieldNum := 1
	for i, p := range props {
		flat := flattenComposite(p.schema)
		protoType := g.protoType(p.name, p.schema)
		fieldName := protoFieldName(p.name)

		constraint := ""
		if g.validate {
			constraint = g.protoConstraint(p.schema)
		}

		if i > 0 {
			fmt.Fprintln(g.w)
		}
		if flat.Description != "" {
			for _, line := range strings.Split(strings.TrimRight(flat.Description, "\n"), "\n") {
				fmt.Fprintf(g.w, "%s  // %s\n", indent, line)
			}
		}

		if protoType.repeated {
			fmt.Fprintf(g.w, "%s  repeated %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		} else if protoType.isMap {
			fmt.Fprintf(g.w, "%s  map<string, %s> %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		} else if protoType.optional {
			fmt.Fprintf(g.w, "%s  optional %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		} else {
			fmt.Fprintf(g.w, "%s  %s %s = %d%s;\n",
				indent, protoType.typeName, fieldName, fieldNum, constraint)
		}
		fieldNum++
	}

	fmt.Fprintf(g.w, "%s}\n\n", indent)
}

type protoTypeInfo struct {
	typeName string
	optional  bool
	repeated  bool
	isMap     bool
}

func (g *protoGen) protoType(contextName string, s *Schema) protoTypeInfo {
	if s == nil {
		return protoTypeInfo{typeName: "string", optional: true}
	}

	if isScalarUnion(s) {
		// Proto doesn't have unions for scalars; use string as the most permissive.
		return protoTypeInfo{typeName: "string", optional: true}
	}

	flat := flattenComposite(s)

	if len(flat.Enum) > 0 {
		return protoTypeInfo{typeName: "string", optional: true}
	}

	// Check format.
	if ft := formatToProtoType(flat.Format); ft != "" {
		return protoTypeInfo{typeName: ft, optional: true}
	}

	switch flat.Type {
	case "string":
		return protoTypeInfo{typeName: "string", optional: true}
	case "integer":
		return protoTypeInfo{typeName: "int64", optional: true}
	case "number":
		return protoTypeInfo{typeName: "double", optional: true}
	case "boolean":
		return protoTypeInfo{typeName: "bool", optional: true}
	case "array":
		inner := g.protoType(contextName+"Item", flat.Items)
		return protoTypeInfo{typeName: inner.typeName, repeated: true}
	case "object":
		if hasProps(flat) {
			return protoTypeInfo{typeName: protoMessageName(contextName), optional: true}
		}
		if flat.AdditionalProperties != nil {
			apFlat := flattenComposite(flat.AdditionalProperties)
			if hasProps(apFlat) {
				return protoTypeInfo{typeName: protoMessageName(contextName) + "Entry", isMap: true}
			}
			inner := g.protoType(contextName+"Entry", flat.AdditionalProperties)
			return protoTypeInfo{typeName: inner.typeName, isMap: true}
		}
		return protoTypeInfo{typeName: "string", isMap: true}
	}

	if hasProps(flat) {
		return protoTypeInfo{typeName: protoMessageName(contextName), optional: true}
	}
	if flat.AdditionalProperties != nil {
		apFlat := flattenComposite(flat.AdditionalProperties)
		if hasProps(apFlat) {
			return protoTypeInfo{typeName: protoMessageName(contextName) + "Entry", isMap: true}
		}
		inner := g.protoType(contextName+"Entry", flat.AdditionalProperties)
		return protoTypeInfo{typeName: inner.typeName, isMap: true}
	}

	return protoTypeInfo{typeName: "string", optional: true}
}

func (g *protoGen) protoConstraint(s *Schema) string {
	if !g.validate {
		return ""
	}

	flat := flattenComposite(s)

	var parts []string

	// String constraints.
	if flat.Type == "string" || flat.Format != "" {
		if flat.Pattern != "" {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.pattern = %q", flat.Pattern))
		}
		if flat.MinLength != nil && *flat.MinLength > 0 {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.min_len = %d", *flat.MinLength))
		}
		if flat.MaxLength != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.max_len = %d", *flat.MaxLength))
		}
		// Format-based pattern.
		if pat := formatToProtoPattern(flat.Format); pat != "" && flat.Pattern == "" {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).string.pattern = %q", pat))
		}
		// Built-in validators.
		switch flat.Format {
		case "ipv4", "ipv4-unicast", "ipv4-multicast", "ipv4-netmask":
			parts = append(parts, "(buf.validate.field).string.ipv4 = true")
		case "ipv6", "ipv6-netmask":
			parts = append(parts, "(buf.validate.field).string.ipv6 = true")
		case "idn-hostname", "domain-name":
			parts = append(parts, "(buf.validate.field).string.hostname = true")
		}
	}

	// Integer constraints.
	if flat.Type == "integer" {
		if flat.Minimum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).int64.gte = %d", int64(*flat.Minimum)))
		}
		if flat.Maximum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).int64.lte = %d", int64(*flat.Maximum)))
		}
	}

	// Number constraints.
	if flat.Type == "number" {
		if flat.Minimum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).double.gte = %v", *flat.Minimum))
		}
		if flat.Maximum != nil {
			parts = append(parts, fmt.Sprintf("(buf.validate.field).double.lte = %v", *flat.Maximum))
		}
	}

	if len(parts) == 0 {
		return ""
	}
	return " [" + strings.Join(parts, ", ") + "]"
}

func formatToProtoType(format string) string {
	switch format {
	case "integer", "integer-id", "sequence-id":
		return "int64"
	case "float", "number":
		return "double"
	default:
		// All other format types are string-based in proto.
		return ""
	}
}

func formatToProtoPattern(format string) string {
	switch format {
	case "mac":
		return `^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`
	case "interface-name", "swp-name", "bond-swp-name", "transceiver-name",
		"bridge-name":
		return `^(swp|eth|bond|br|lo|vlan|peerlink|erspan|mgmt)[a-zA-Z0-9_./-]*$`
	case "vrf-name":
		return `^[a-zA-Z][a-zA-Z0-9_-]{0,14}$`
	case "vlan-range":
		return `^[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*$`
	case "ip-port-range":
		return `^[0-9]+(-[0-9]+)?$`
	case "route-distinguisher":
		return `^(\d+\.\d+\.\d+\.\d+:\d+|\d+:\d+)$`
	case "route-target", "route-target-any":
		return `^(\d+\.\d+\.\d+\.\d+:\d+|\d+:\d+)$`
	case "ext-community":
		return `^(rt|soo|bandwidth)\s+\S+$`
	case "community", "well-known-community", "large-community":
		return `^(\d+:\d+|no-export|no-advertise|local-AS|no-peer|blackhole|graceful-shutdown|accept-own|internet)$`
	case "es-identifier":
		return `^([0-9A-Fa-f]{2}:){9}[0-9A-Fa-f]{2}$`
	case "segment-identifier":
		return `^\d+$`
	case "user-name":
		return `^[a-z_][a-z0-9_-]*[$]?$`
	case "snmp-branch", "oid":
		return `^\.?(\d+\.)*\d+$`
	default:
		return ""
	}
}

func protoMessageName(s string) string {
	parts := strings.FieldsFunc(s, func(c rune) bool {
		return c == '-' || c == '_' || c == '.'
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func protoFieldName(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	// Proto field names must start with a letter.
	if len(s) > 0 && s[0] >= '0' && s[0] <= '9' {
		s = "x_" + s
	}
	return s
}

func newProtobufFormat() *Format {
	var validate bool
	return &Format{
		Name:        "protobuf",
		Aliases:     []string{"proto"},
		Description: "Proto3 messages",
		Flags: func(fs *flag.FlagSet) {
			fs.BoolVar(&validate, "validate", false, "Include buf protovalidate constraints")
		},
		Write: func(w io.Writer, schema *Schema, info map[string]any) error {
			return WriteProtobuf(w, schema, info, validate)
		},
	}
}
